# Generated by Django 6.0.3 on 2026-03-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalIrabRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100, verbose_name="الكلمة")),
                (
                    "normalized_word",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="الكلمة المعيارية"
                    ),
                ),
                ("sentence", models.TextField(verbose_name="الجملة")),
                ("word_order", models.PositiveIntegerField(verbose_name="الترتيب")),
                (
                    "grammatical_type",
                    models.CharField(max_length=100, verbose_name="النوع النحوي"),
                ),
                ("irab", models.TextField(verbose_name="الإعراب")),
                ("reason", models.TextField(verbose_name="السبب")),
                (
                    "sentence_irab_summary",
                    models.TextField(verbose_name="ملخص إعراب الجملة"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل إعراب عالمي",
                "verbose_name_plural": "سجل الإعراب العالمي",
                "ordering": ["-created_at"],
            },
        ),
    ]
