# Generated by Django 6.0.3 on 2026-03-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_globalirabrecord"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grammarnote",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "تعليمة نحوية",
                "verbose_name_plural": "تعليمات نحوية ",
            },
        ),
    ]
